import type * as A from './ast.js';

class Env {
 constructor(public parent?:Env, private values=new Map<string,unknown>()){}
 define(name:string,value:unknown){this.values.set(name,value);}
 get(name:string):unknown{if(this.values.has(name))return this.values.get(name);if(this.parent)return this.parent.get(name);throw new Error(`ARR runtime: unknown name '${name}'`);}
 set(name:string,value:unknown){if(this.values.has(name)){this.values.set(name,value);return;}if(this.parent){this.parent.set(name,value);return;}throw new Error(`ARR runtime: unknown name '${name}'`);}
}
class ReturnSignal {constructor(public value:unknown){}}
export class Runtime {
 readonly global=new Env();
 private boot:A.BlockStmt[]=[];
 constructor(){this.global.define('print',(...xs:unknown[])=>console.log(...xs));this.global.define('println',(...xs:unknown[])=>console.log(...xs));this.global.define('len',(x:any)=>x?.length??0);this.global.define('typeOf',(x:unknown)=>Array.isArray(x)?'array':x===null?'none':typeof x);}
 run(program:A.Program){for(const statement of program.body)this.exec(statement,this.global);for(const block of this.boot)this.exec(block,this.global);}
 private exec(s:A.Stmt,env:Env):unknown{switch(s.kind){case'VarDecl':{const value=s.value?this.eval(s.value,env):undefined;this.typeCheck(s.type,value);env.define(s.name,value);return;}case'ExprStmt':return this.eval(s.expr,env);case'Block':{const local=new Env(env);for(const x of s.body)this.exec(x,local);return;}case'If':{if(this.eval(s.test,env))this.exec(s.consequent,env);else if(s.alternate)this.exec(s.alternate,env);return;}case'While':{let guard=0;while(this.eval(s.test,env)){this.exec(s.body,env);if(++guard>100000)throw new Error('ARR runtime: loop guard exceeded');}return;}case'Return':throw new ReturnSignal(s.value?this.eval(s.value,env):undefined);case'FnDecl':env.define(s.name,(...args:unknown[])=>{const local=new Env(env);s.params.forEach((p,i)=>local.define(p,args[i]));try{for(const x of s.body.body)this.exec(x,local);}catch(e){if(e instanceof ReturnSignal)return e.value;throw e;}return undefined;});return;case'Boot':this.boot.push(s.body);return;case'Import':return;case'Component':env.define(s.name,{kind:'component',name:s.name,body:s.body});return;case'KernelPanic':throw new Error('ARR runtime: privileged stop requested');case'Reboot':throw new Error('ARR runtime: restart requested');}}
 private eval(e:A.Expr,env:Env):unknown{switch(e.kind){case'Literal':return e.value;case'Identifier':return env.get(e.name);case'Array':return e.items.map(x=>this.eval(x,env));case'Unary':{const v:any=this.eval(e.expr,env);return e.op==='!'?!v:e.op==='-'?-v:+v;}case'Binary':{const a:any=this.eval(e.left,env),b:any=this.eval(e.right,env);switch(e.op){case'+':return a+b;case'-':return a-b;case'*':return a*b;case'/':return a/b;case'%':return a%b;case'==':return a===b;case'!=':return a!==b;case'<':return a<b;case'<=':return a<=b;case'>':return a>b;case'>=':return a>=b;case'&&':return a&&b;case'||':return a||b;default:throw new Error(`ARR runtime: unknown operator ${e.op}`);}}case'Assignment':{if(e.target.kind!=='Identifier')throw new Error('ARR runtime: assignment target must be a name');const old:any=env.get(e.target.name),value:any=this.eval(e.value,env);const next=e.op==='='?value:e.op==='+='?old+value:e.op==='-='?old-value:e.op==='*='?old*value:old/value;env.set(e.target.name,next);return next;}case'Call':{const fn:any=this.eval(e.callee,env);if(typeof fn!=='function')throw new Error('ARR runtime: value is not callable');return fn(...e.args.map(x=>this.eval(x,env)));}case'Member':{const obj:any=this.eval(e.object,env);if(obj==null&&e.optional)return undefined;if(obj==null)throw new Error('ARR runtime: member access on none');return obj[e.property];}}}
 private typeCheck(type:string|undefined,value:unknown){if(!type||type==='any')return;const t=type.replace('?','');const ok=t==='string'?typeof value==='string':t==='bool'?typeof value==='boolean':t.startsWith('uint')||t.startsWith('int')?typeof value==='number'&&Number.isInteger(value):t==='float'||t==='double'?typeof value==='number':true;if(!ok)throw new Error(`ARR type error: expected ${type}`);}
}
